# Generated by Django 5.2.5 on 2025-08-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cover", models.ImageField(blank=True, upload_to="")),
                ("artist", models.CharField(max_length=100)),
                ("title", models.CharField(max_length=100)),
                ("rating", models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
    ]
